baseURL = 'https://stororokw.github.io/'
languageCode = 'en-US'
title = 'stororokw'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
